### PR TITLE
README.MD: added description, tech stack, contribution procedure,contributors list

### PR DESCRIPTION
**Pull request by KumarSanu8**
README.MD: added description, tech stack, contribution procedure,contributors list

### CODE REVIEW

**Comment by ratnakar5938** [comment]
U have to make another branch in ur fork

**Comment by ratnakar5938** [comment]
- Copy the readme file to any other location in ur local system
- Then delete the repository in GitHub
- Then delete the local repository
- Then fork it again and make a new branch for the readme so that after I merge ur PR it won't conflict in ur forked repository

**Comment by ratnakar5938** [comment]
I will provide u links for screenshot soon

**Comment by KumarSanu8** [comment]
> I will provide u links for screenshot soon

created new branch as "secondary" and pull request

**Review by ratnakar5938 — COMMENTED** [review]
Need to change the branch

**Pull request closed without merging**
